--Exercicio 01: 
SELECT 
    IDEMPREGADO,
    NOMEEMPREGADO,
    (2020 - 1981) AS ANOS_NA_EMPRESA
FROM 
    EMPREGADO
WHERE 
    EXTRACT(YEAR FROM DATAADMISSAO) = 1981
	
--Exercicio 02: 
SELECT 
    MAX(CARGO) AS CARGO
FROM
    EMPREGADO
	
--Exercicio 03: 
SELECT UF,
    COUNT(1) AS TOTAL
FROM 
    CIDADE
GROUP BY 
    uf 
ORDER BY 
    total DESC
	
--Exercicio 04:
INSERT INTO DEPARTAMENTO VALUES (100, 'INOVAÇÃO', 'SAO LEOPOLDO')
UPDATE 
    EMPREGADO 
SET 
    IDDEPARTAMENTO = 100
WHERE EXTRACT(MONTH FROM DATAADMISSAO) = 12 AND CARGO <> 'ATENDENTE'
