--Exercicio 01:
SELECT emp.NOMEEMPREGADO, dep.NOMEDEPARTAMENTO, gerente.NOMEEMPREGADO AS GERENTE FROM EMPREGADO emp
JOIN DEPARTAMENTO dep ON emp.IDDEPARTAMENTO = dep.IDDEPARTAMENTO
JOIN EMPREGADO gerente ON  gerente.IDEMPREGADO = emp.IDGERENTE

--Exercicio 02:
SELECT emp.NOMEEMPREGADO, dep.NOMEDEPARTAMENTO, MAX(emp.SALARIO) AS SALARIO FROM EMPREGADO emp
JOIN DEPARTAMENTO dep ON emp.IDDEPARTAMENTO = dep.IDDEPARTAMENTO
GROUP BY emp.NOMEEMPREGADO, dep.NOMEDEPARTAMENTO
ORDER BY SALARIO DESC
FETCH NEXT 1 ROW ONLY

--Exercicio 03:
CREATE TABLE empregadoBackup AS SELECT * FROM empregado;

MERGE INTO empregado e
    USING (SELECT * FROM empregado e 
        WHERE e.idDepartamento 
        IN (SELECT idDepartamento 
            FROM departamento
            WHERE localizacao = 'SAO PAULO')) d
    ON (e.idEmpregado = d.idEmpregado)
    WHEN MATCHED THEN
        UPDATE SET e.salario = d.salario * 1.173;


--Exercicio 04:
SELECT NOME, UF FROM CIDADEEX 
GROUP BY NOME, UF
HAVING COUNT (NOME, UF) > 1

--Exercicio 05:

UPDATE CIDADEEX SET NOME = RPAD(NOME, LENGTH(NOME)+1, '*') WHERE IDCIDADE IN (SELECT MAX(IDCIDADE)
FROM (SELECT IDCIDADE, NOME, UF
    FROM CIDADEEX WHERE NOME IN (SELECT NOME 
    FROM (SELECT NOME, UF, COUNT (NOME) AS QUANTIDADE FROM CIDADEEX GROUP BY NOME, UF HAVING COUNT(NOME) > 1))) GROUP BY NOME)