CREATE TABLE PRODUTOEX
(
	COD_IDENTIFICACAO NUMBER(38),
	NOME_CURTO VARCHAR(50),
	NOME_DESCRITIVO VARCHAR(200),
	DATA_CRIACAO DATE,
	LOCAL_ESTOQUE NUMBER(38),
	QUANTIDADE NUMBER(38),
	PRECO NUMBER(38, 38),
)

CREATE TABLE ESTOQUEEX
(
	COD_IDENTIFICACAO NUMBER(38),
	NOME_ESTOQUE VARCHAR(50),
	DATA_CRIACAO DATE,
	CAPACIDADE NUMBER(38),
	ATIVO VARCHAR(1)
)

ALTER TABLE PRODUTOEX
ALTER COLUMN COD_IDENTIFICACAO INT

ALTER TABLE PRODUTOEX
RENAME COLUMN LOCAL_ESTOQUE TO ID_ESTOQUE

ALTER TABLE PRODUTOEX
ADD CONSTRAINT PK_COD PRIMARY KEY (COD_IDENTIFICACAO)

ALTER TABLE PRODUTOEX
ADD CONSTRAINT FK_COD 
FOREIGN KEY (ID_ESTOQUE) REFERENCES ESTOQUEEX

ALTER TABLE PRODUTOEX
RENAME TO PRODUTOEX1 

ALTER TABLE ESTOQUEEX
RENAME TO ESTOQUEEX1