--EXERCICIO 01:
SELECT 
    IDPEDIDO,
    IDCLIENTE,
    DATAPEDIDO,
    VALORPEDIDO,
    SITUACAO
FROM
    PEDIDO
WHERE   
    SITUACAO = 'A' AND IDCLIENTE = 11518 OR VALORPEDIDO > 9000
ORDER BY 
    VALORPEDIDO

--EXERCICIO 02:
SELECT * FROM MATERIAL
WHERE 
    PESOLIQUIDO > 4 AND PRECOCUSTO < 00.30
	
--EXERCICIO 03:
SELECT DISTINCT(nome)
    NOME,
    UF
FROM 
    CIDADE
WHERE
    UF = 'RS'
ORDER BY
    NOME
	
--EXERCICIO 04:
SELECT idPedido
FROM pedidoItem
WHERE idPedido IN 
(
    SELECT idPedido FROM pedido 
    WHERE valorPedido = 480.25 AND situacao = 'Q'
) 
ORDER BY precoUnitario

--EXERCICIO 05:
SELECT * FROM CLIENTE
WHERE
    CEP IS NULL AND SITUACAO = 'A'
	
--EXERCICIO 06
SELECT 
    IDPEDIDO,
    (QUANTIDADE * PRECOUNITARIO) AS CALCULODOVALOR,
    IDPRODUTO  
FROM 
    PEDIDOITEM
WHERE
    IDPEDIDO = 168

--EXERCICIO 07
SELECT * FROM MATERIAL
WHERE
    PESOLIQUIDO BETWEEN 0.5 AND 0.6

--EXERCICIO 08
SELECT * FROM PEDIDO 
WHERE
    SITUACAO = 'A' AND VALORPEDIDO > 9500.00
	
--EXERCICIO 09
SELECT
    idmaterial,
    ( quantidade * 5 ),
    quantidade
FROM
    produtomaterial
WHERE
    idproduto = 2492
	
--EXERCICIO 10
SELECT * FROM PEDIDO
WHERE   
    SITUACAO IN('A', 'C', 'I') AND VALORPEDIDO >= 9800.00
    