CREATE TABLE ALUNOAULA1
(
    NOME VARCHAR(200),
    DATA_NASCIMENTO DATE,
    CIDADE VARCHAR(50),
    CPF NUMBER(38),
    MATRICULA NUMBER(38),
    CURSO_MATRICULADO VARCHAR(200)
)

CREATE TABLE CURSOAULA1 
(
    NOME VARCHAR(200),
    DIA DATE,
    SITUACAO VARCHAR(200),
    PRE_REQUISITOS VARCHAR(200),
    LUGAR VARCHAR(200)
)

ALTER TABLE CURSOAULA1 
ADD VALOR NUMBER(38,38)

ALTER TABLE ALUNOAULA1
ADD CONSTRAINT PK_ALUNO PRIMARY KEY(NOME)

ALTER TABLE CURSOAULA1
ADD CONSTRAINT PK_CURSO PRIMARY KEY(NOME)