--Exercicio 1: 
CREATE TABLE CidadeAux
(
  IDCidade  INT        NOT NULL,
  Nome      VARCHAR2(30) NOT NULL,
  UF        VARCHAR2(2)  NOT NULL,
    CONSTRAINT PK_CidadeAux1 PRIMARY KEY(IDCidade)
);	

SELECT * FROM CidadeEx

--Exercicio 2: 
TRUNCATE TABLE CidadeAux
INSERT INTO CidadeAux
SELECT * FROM CidadeEx
WHERE UF = 'RS'

--Exercicio 3: 
INSERT INTO ESTOQUEEX1
(COD_ID, NOME_ESTOQUE, DATA_CRIACAO, CAPACIDADE, ATIVO)
VALUES
(1, 'produto teste', SYSDATE, 20, 'S')

--Exercicio 4: 
INSERT INTO PRODUTOEX1
(ID_PRODUTO, NOME, NOME_DESCRITIVO, DATA_CRIACAO, ID_ESTOQUE, QUANTIDADE, PRECO)
VALUES
(1, 'produto', 'limpador', SYSDATE, 1, 28, 25.20)

INSERT INTO  PRODUTOEX1
(ID_PRODUTO, NOME, NOME_DESCRITIVO, DATA_CRIACAO, ID_ESTOQUE, QUANTIDADE, PRECO)
VALUES
(2, 'produto', 'secadora', SYSDATE, 1, 28, 27.50)

--Exercicio 5:
UPDATE
ASSOCIADOEX
SET
CPF = '03326173000',
ENDERECO = 'Rua teste',
BAIRRO = 'bairro teste',
COMPLEMENTO = 'bloco 1',
IDCIDADE = 1
WHERE
IDASSOCIADO = 1

--Exercicio 6: 
DELETE FROM CIDADEEX WHERE IDCIDADE = 8

DELETE FROM CIDADEEX WHERE IDCIDADE = 4