--Exercicio 01: 
SELECT cidade.NOME AS CIDADE, cont.NOME AS CONTRATANTE,
CASE
    WHEN ESFERA = 'M' THEN 'Municipal'
    WHEN ESFERA = 'E' THEN 'Estadual' 
END AS ESTADUAL
FROM LIC_CONTRATANTE cont
JOIN LIC_CIDADE cidade ON cidade.IDCIDADE = cont.IDCIDADE
WHERE cidade.NOME = 'Santos' AND cidade.UF = 'SP'

--Exercicio 02:
SELECT emp.NOME AS EMPRESA, cidade.NOME AS CIDADE FROM LIC_EMPRESA emp
JOIN LIC_CIDADE cidade ON emp.IDCIDADE = cidade.IDCIDADE
WHERE CNPJ LIKE '%86'

--Exercicio 03:
SELECT mat.NOME, item.QUANTIDADE, SUM((item.VALOR_MINIMO + item.VALOR_MAXIMO)* item.QUANTIDADE)AS VALORMEDIOTOTAL
FROM LIC_MATERIAL mat
JOIN LIC_ITEM_LICITACAO item ON item.IDMATERIAL = mat.IDMATERIAL
JOIN LIC_LICITACAO lic ON item.IDLICITACAO = lic.IDLICITACAO
WHERE lic.IDLICITACAO = 60
GROUP BY mat.NOME, item.QUANTIDADE

--Exercicio 04: 

SELECT lic.TITULO, lic.INICIO_VIGENCIA, item.QUANTIDADE, mat.NOME AS MATERIAL, classe.NOME AS CLASSE FROM LIC_LICITACAO lic
JOIN LIC_ITEM_LICITACAO item ON item.IDLICITACAO = lic.IDLICITACAO
JOIN LIC_MATERIAL mat ON item.IDMATERIAL = mat.IDMATERIAL
JOIN LIC_CLASSE_MATERIAL classe ON classe.IDCLASSE_MATERIAL = mat.IDCLASSE_MATERIAL
WHERE lic.IDCONTRATANTE = 408

--Exercicio 05:
SELECT (MAX(VALOR_FINAL) - MIN(VALOR_FINAL)) "DIFERENÇA",
    IDLICITACAO "ID"
    FROM LIC_PROPOSTA
    GROUP BY IDLICITACAO
    ORDER BY "DIFERENÇA" DESC;

--Exercicio 06
SELECT lp.IDPROPOSTA, lp.DATA_INSCRICAO, le.NOME AS EMPRESA, c.NOME AS CIDADE, c.UF, le.CNPJ, le.CPF, ll.TITULO, 
ll.SITUACAO, li.QUANTIDADE, li.OBSERVACAO, lm.NOME AS MATERIAL
FROM
    lic_proposta         lp
    INNER JOIN lic_empresa          le ON lp.idempresa = le.idempresa
    INNER JOIN cidade               c ON le.idcidade = c.idcidade
    INNER JOIN lic_licitacao        ll ON lp.idlicitacao = ll.idlicitacao
    INNER JOIN lic_item_licitacao   li ON ll.idlicitacao = li.idlicitacao 
    INNER JOIN lic_material         lm ON li.idmaterial = lm.idmaterial
	
--Exercicio 07:
SELECT * FROM MATERIAL material
JOIN LIC_ITEM_LICITACAO item ON material.IDMATERIAL != item.IDMATERIAL

--Exercicio 08: 	
-- NO CHECK DE ESFERA NÃO PERMITE O 'T', APENAS ('E', 'F', 'M')
INSERT INTO lic_contratante (NOME,IDCIDADE,ESFERA) VALUES ('Teste1',3812,'T');

-- NÃO ACHOU A CHAVE ESTRANGEIRA DE CIDADE!
INSERT INTO lic_contratante (NOME,IDCIDADE,ESFERA) VALUES ('Teste2',9999,'E');

-- CUMPRIU COM TUDO, PASSOU NA VERIFICAÇÃO, INSERIU A CHAVE PRIMÁRIA AUTOMATICAMENTE.
INSERT INTO lic_contratante (IDCONTRATANTE,NOME,IDCIDADE,ESFERA) VALUES (9999,'Teste3',3812,'E');

-- CUMPRIU COM TUDO TAMBÉM, INSERIU A CHAVE PRIMÁRIA AUTOMATICAMENTE!
INSERT INTO lic_contratante (NOME,IDCIDADE,ESFERA) VALUES ('Teste4',3812,'E');
	

