--Exercicio 01:
SELECT TO_CHAR(DATA_FECHAMENTO, 'DD-mon-YYYY') AS DATAFECHAMENTO,
    ROUND(VALOR_ESTIMADO_MIN, 0) AS VALORESTIMADO,
    TITULO
FROM 
    LIC_LICITACAO 
WHERE INICIO_VIGENCIA >= '01/01/2018' AND FIM_VIGENCIA <= '30/06/2018'

--Exercicio 02:
SELECT IDCONTRATANTE,
    AVG(VALOR_ESTIMADO_MIN) AS VALORMINMEDIOESTIMADO,
    AVG(VALOR_ESTIMADO_MAX) AS VALORMAXMEDIOESTIMADO
    FROM LIC_LICITACAO WHERE IDCONTRATANTE IN (705, 738)
    GROUP BY IDCONTRATANTE
	
--Exercicio 03: 
SELECT * FROM
    (SELECT IDCONTRATANTE,
    COUNT(IDCONTRATANTE) AS NUMDEVEZES
    FROM LIC_LICITACAO
    GROUP BY IDCONTRATANTE
    ORDER BY NUMDEVEZES DESC)
    WHERE ROWNUM <= 6;
	
--Exercicio 04:
SELECT REPLACE(REPLACE(REPLACE(SITUACAI, 'D', 'DESQUALIFICADA'),'S','SELECIONADA' ),'N', 'NÃO SELECIONADA') 
	AS, IDLICITACAO AS ID_LICITACAO, IDPROPOSTA AS ID_PROPOSTA FROM LIC_PROPOSTA
WHERE 
	DATA_INSCRICAO >= '01/06/2018'
--Exercicio 5.1:
SELECT IDPROPOSTA AS PROPOSTA,
    TRUNC(VALOR_INICIAL, 0) AS VALORINICIAL,
    TRUNC(VALOR_FINAL, 0) AS VALORFINAL
    FROM LIC_PROPOSTA;

--Exercicio 5.2
SELECT IDLICITACAO AS LICITACAO,
    TRUNC(MAX(VALOR_FINAL)) AS MAIORVALOR
    FROM LIC_PROPOSTA
    GROUP BY IDLICITACAO
    ORDER BY MAIORVALOR DESC
	
--Exercicio 06:

    SELECT SITUACAO,
    TO_CHAR(DATA_INSCRICAO, 'MM-YYYY') AS MESANO, 
    COUNT(IDPROPOSTA) AS QUANTIDADEPROPOSTA
    FROM LIC_PROPOSTA
    WHERE EXTRACT(YEAR FROM DATA_INSCRICAO) = 2018
    GROUP BY TO_CHAR(DATA_INSCRICAO, 'MM-YYYY'),SITUACAO
	ORDER BY MESANO, SITUACAO;

--Exercicio 07:
SELECT * FROM LIC_MATERIAL WHERE IDCLASSE_MATERIAL = 13 AND  NOME LIKE '%ALTURA 925 MM'	
	
--Exercicio 08:
    SELECT IDITEM_LICITACAO,
    IDLICITACAO,
    QUANTIDADE,
    VALOR_MINIMO,
    (VALOR_MINIMO * QUANTIDADE) AS VALORMINTOTAL,
    (VALOR_MAXIMO * QUANTIDADE) AS VALORMAXTOTAL
    FROM LIC_ITEM_LICITACAO
    ORDER BY IDLICITACAO 