--Exercicio 01:
SELECT quest.TITULO AS QUESTIONARIO, questao.DESCRICAO AS DESCRICAO_QUESTAO, SUM(op.IDQUESTAO) AS RANKING
FROM QUESTIONARIO quest
JOIN QUESTAO questao ON quest.IDQUESTIONARIO = questao.IDQUESTIONARIO
JOIN OPCAO op ON op.IDQUESTAO = questao.IDQUESTAO
GROUP BY quest.TITULO, questao.DESCRICAO
ORDER BY RANKING DESC
FETCH NEXT 1 ROW ONLY

--Exercicio 02:
SELECT * FROM QUESTIONARIO quest 
JOIN PREREQUISITO req ON quest.IDQUESTIONARIO = req.IDQUESTIONARIO

--Exercicio 03:
SELECT
    EXTRACT(MONTH FROM q.DATAULTIMAALTERACAO) AS MES,
    COUNT(1)
FROM
    QUESTAO q
GROUP BY
    EXTRACT(MONTH FROM q.DATAULTIMAALTERACAO)
HAVING
    COUNT(1) = 1
ORDER BY MES;


