--Exercicio 01: 
INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Angela', SYSDATE , 'São Leopoldo', 60905285107, 17289, 'Analise de Sistemas')

INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Arthur', SYSDATE, 'São Leopoldo', 03067542150, 23564, 'Ciência da Computação')

INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Guilherme', SYSDATE, 'São Leopoldo', 20464204119, 58996, 'Sistemas para internet')

INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Pedro', SYSDATE, 'Porto Alegre', 79246474147, 58993, 'Enfermagem')

INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Mateus', SYSDATE, 'São Leopoldo', 06542742158, 89556, 'Psicologia')

INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Marcelo', SYSDATE, 'Novo Hamburgo', 49342347161, 78896, 'Engenharia Eletrica')

INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Leonardo', SYSDATE, 'São Leopoldo', 23183014173, 55662, 'Medicina')

INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Rafael', SYSDATE, 'Canoas', 62502882109, 55663, 'Gastronomia')

INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Gabriel', SYSDATE, 'Sapucaia do Sul', 40545931193, 55664, 'Gastronomia')

INSERT INTO ALUNOAULA1
(NOME, DATA_NASCIMENTO, CIDADE, CPF, MATRICULA, CURSO_MATRICULADO)
VALUES
('Kreonardo', SYSDATE, 'Sapucaia do Sul', 79209937171, 55665, 'Quimica')

---Exercicio 02:
INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('JavaScript', SYSDATE , 'S', 'OO', 'LUGAR', 25.50)

INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('React', SYSDATE , 'S', 'JavaScript', 'LUGAR', 27.50)

INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('Banco de Dados', SYSDATE , 'S', 'React', 'LUGAR', 28.90)

INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('HTML/CSS', SYSDATE , 'S', 'OO', 'LUGAR', 30.00)

INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('Java', SYSDATE , 'S', 'React', 'LUGAR', 40.00)

INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('C#', SYSDATE , 'S', 'Java', 'LUGAR', 50.00)

INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('Segurança Web', SYSDATE , 'S', 'C#', 'LUGAR', 40.00)

INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('Engenharia', SYSDATE , 'S', 'Segurança Web', 'LUGAR', 80.00)

INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('PHP', SYSDATE , 'S', 'Engenharia', 'LUGAR', 25.50)

INSERT INTO CURSOAULA1
(NOME, DIA, SITUACAO, PRE_REQUISITOS, LUGAR, VALOR)
VALUES
('Ruby', SYSDATE , 'S', 'PHP', 'LUGAR', 28.50)

---Exercicio 03: 
UPDATE
CURSOAULA1
SET
SITUACAO = 'S'
WHERE
SITUACAO = 'N'

--EXERCICIO 04:
UPDATE
CLIENTE
SET
SITUACAO = 'A'
WHERE
SITUACAO = 'I'

--Exercicio 05:
DELETE FROM ASSOCIADOEX WHERE SEXO = 'M'
