
 CREATE TABLE "USUARIO" (
	"ID" NUMBER(38) NOT NULL,
	"NOME_COMPLETO" VARCHAR2(255) NOT NULL,
	"EMAIL" VARCHAR2(255) UNIQUE NOT NULL,
	"APELIDO" VARCHAR2(50),
	"DATA_NASCIMENTO" DATE NOT NULL,
	"SENHA" VARCHAR2(128) NOT NULL,
	"IMAGEM_PERFIL" VARCHAR2(512),
	constraint USUARIO_PK PRIMARY KEY ("ID"));

CREATE sequence "USUARIO_ID_SEQ";

CREATE trigger "BI_USUARIO_ID"
  before insert on "USUARIO"
  for each row
begin
  select "USUARIO_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "POSTAGEM" (
	"ID" NUMBER(38) NOT NULL,
	"ID_USUARIO" NUMBER(38) NOT NULL,
	"TEXTO" VARCHAR2(4000) NOT NULL,
	"IMAGEM" VARCHAR2(512) NOT NULL,
	constraint POSTAGEM_PK PRIMARY KEY ("ID"));

CREATE sequence "POSTAGEM_ID_SEQ";

CREATE trigger "BI_POSTAGEM_ID"
  before insert on "POSTAGEM"
  for each row
begin
  select "POSTAGEM_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "AMIGO" (
	"ID" NUMBER(38) NOT NULL,
	"ID_USUARIO" NUMBER(38) NOT NULL,
	"ID_AMIGO" NUMBER(38) NOT NULL,
	"ACEITO" NUMBER(1) NOT NULL,
	constraint AMIGO_PK PRIMARY KEY ("ID"));

CREATE sequence "AMIGO_ID_SEQ";

CREATE trigger "BI_AMIGO_ID"
  before insert on "AMIGO"
  for each row
begin
  select "AMIGO_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "COMENTARIO" (
	"ID" NUMBER(38) NOT NULL,
	"ID_USUARIO" NUMBER(38) NOT NULL,
	"ID_POSTAGEM" NUMBER(38) NOT NULL,
	"TEXTO" VARCHAR2(4000) NOT NULL,
	"IMAGEM" VARCHAR2(512) NOT NULL,
	constraint COMENTARIO_PK PRIMARY KEY ("ID"));

CREATE sequence "COMENTARIO_ID_SEQ";

CREATE trigger "BI_COMENTARIO_ID"
  before insert on "COMENTARIO"
  for each row
begin
  select "COMENTARIO_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/
CREATE TABLE "CURTIDA" (
	"ID" NUMBER(38) NOT NULL,
	"ID_POSTAGEM" NUMBER(38) NOT NULL,
	"ID_USUARIO" NUMBER(38) NOT NULL,
	constraint CURTIDA_PK PRIMARY KEY ("ID"));

CREATE sequence "CURTIDA_ID_SEQ";

CREATE trigger "BI_CURTIDA_ID"
  before insert on "CURTIDA"
  for each row
begin
  select "CURTIDA_ID_SEQ".nextval into :NEW."ID" from dual;
end;

/

ALTER TABLE "POSTAGEM" ADD CONSTRAINT "POSTAGEM_fk0" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID");

ALTER TABLE "AMIGO" ADD CONSTRAINT "AMIGO_fk0" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID");
ALTER TABLE "AMIGO" ADD CONSTRAINT "AMIGO_fk1" FOREIGN KEY ("ID_AMIGO") REFERENCES "USUARIO"("ID");

ALTER TABLE "COMENTARIO" ADD CONSTRAINT "COMENTARIO_fk0" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID");
ALTER TABLE "COMENTARIO" ADD CONSTRAINT "COMENTARIO_fk1" FOREIGN KEY ("ID_POSTAGEM") REFERENCES "POSTAGEM"("ID");

ALTER TABLE "CURTIDA" ADD CONSTRAINT "CURTIDA_fk0" FOREIGN KEY ("ID_POSTAGEM") REFERENCES "POSTAGEM"("ID");
ALTER TABLE "CURTIDA" ADD CONSTRAINT "CURTIDA_fk1" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID");